<?php
header("Access-Control-Allow-Origin: http://localhost:5184");
header("Access-Control-Allow-Credentials: true");
header("Access-Control-Allow-Methods: POST, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type");
header("Content-Type: application/json");

// Handle preflight options requests
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    exit(0);
}

// 🗂️ FIXED MANUAL IMPORT PATHWAY (Stepping up one folder out of /api)
define('MAILER_DIR', __DIR__ . '/../PHPMailer/');

if (file_exists(MAILER_DIR . 'PHPMailer.php')) {
    require_once MAILER_DIR . 'Exception.php';
    require_once MAILER_DIR . 'PHPMailer.php';
    require_once MAILER_DIR . 'SMTP.php';
} else {
    echo json_encode([
        "success" => false, 
        "message" => "Critical Error: PHPMailer files not detected in: " . MAILER_DIR
    ]);
    exit();
}

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

// Establish database connection block
$conn = new mysqli("localhost", "root", "", "db_appsets");
if ($conn->connect_error) {
    echo json_encode(["success" => false, "message" => "Database connection breakdown: " . $conn->connect_error]);
    exit();
}

$inputData = json_decode(file_get_contents("php://input"), true);

if (!isset($inputData['sender_name']) || !isset($inputData['sender_email']) || !isset($inputData['message_text'])) {
    echo json_encode(["success" => false, "message" => "All form fields are strictly required."]);
    exit();
}

$sender_name = $conn->real_escape_string($inputData['sender_name']);
$sender_email = $conn->real_escape_string($inputData['sender_email']);
$message_text = $conn->real_escape_string($inputData['message_text']);

// Save copy to database table structure safely
$table_check = $conn->query("SHOW TABLES LIKE 'tb_inquiries'");
if ($table_check->num_rows > 0) {
    $stmt = $conn->prepare("INSERT INTO tb_inquiries (sender_name, sender_email, message_text) VALUES (?, ?, ?)");
    $stmt->bind_param("sss", $sender_name, $sender_email, $message_text);
    $stmt->execute();
    $stmt->close();
}

// --- 📧 PHPMailer EMAIL SYSTEM ---
$mail = new PHPMailer(true);
try {
    // Server SMTP configuration settings
    $mail->isSMTP();
    $mail->Host       = 'smtp.gmail.com';
    $mail->SMTPAuth   = true;
    $mail->Username   = 'santosjm62904@gmail.com'; 
    $mail->Password   = 'sief nmae lsst ermn'; // Your secure 16-character Google App Password
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
    $mail->Port       = 587;

    // Delivery Routing Address Targets
    $mail->setFrom('santosjm62904@gmail.com', "C'Smiles System Mailer");
    $mail->addAddress('santosjm62904@gmail.com'); 
    $mail->addReplyTo($sender_email, $sender_name);

    // Email Body Formatting Layout Markup
    $mail->isHTML(true);
    $mail->Subject = "New Patient Inquiry from " . $sender_name;
    
    $clean_message = nl2br(htmlspecialchars($message_text));
    $mail->Body = "
    <html>
    <body style='font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;'>
        <div style='background-color: #ffffff; padding: 30px; border-radius: 15px; max-width: 600px; margin: 0 auto; box-shadow: 0 4px 10px rgba(0,0,0,0.05);'>
            <h2 style='color: #c5a043; border-bottom: 2px solid #f0f0f0; padding-bottom: 10px; margin-top: 0;'>New Website Inquiry Received</h2>
            <p><strong>Patient Name:</strong> {$sender_name}</p>
            <p><strong>Patient Email:</strong> <a href='mailto:{$sender_email}'>{$sender_email}</a></p>
            <div style='background-color: #f9f9f9; padding: 15px; border-left: 4px solid #1cb9d0; border-radius: 4px; margin-top: 20px;'>
                <p style='margin: 0; font-weight: bold; color: #555; margin-bottom: 8px;'>Message Content:</p>
                <p style='margin: 0; line-height: 1.6; color: #333;'>{$clean_message}</p>
            </div>
            <p style='font-size: 11px; color: #aaa; margin-top: 30px; text-align: center; border-top: 1px solid #eeeeee; padding-top: 15px;'>
                This message was auto-generated by the C'Smiles Dental Center Booking Management System.
            </p>
        </div>
    </body>
    </html>";

    $mail->send();
    echo json_encode(["success" => true, "message" => "Thank you! Your message has been sent to our desk successfully."]);

} catch (Exception $e) {
    echo json_encode([
        "success" => false, 
        "message" => "Inquiry log saved to database, but mail delivery failed.",
        "error_details" => $mail->ErrorInfo
    ]);
}

$conn->close();
exit();
?>